<?php

declare(strict_types=1);

/**
 * Data strings for translators — GENERATED by `php build/i18n-data.php`; do not edit.
 *
 * Skill manifests and the starter workflow catalogue stay English at runtime,
 * and the admin translates them as it prints them through nibwp_i18n_data().
 * These literal calls exist only so make-pot extracts them. Nothing requires
 * this file, and it returns before any call could run.
 */

if (!defined('ABSPATH')) {
    exit();
}

return;

/* translators: Skill feature: breakdance-pro */
__('"Did you mean" suggestions when an element slug is wrong', 'nibwp');
/* translators: Skill feature: seo-pro */
__('404 → 301 redirect suggestions', 'nibwp');
/* translators: Workflow when to use: seo-full-audit */
__('A complete SEO health check of a site or a section.', 'nibwp');
/* translators: Workflow when to use: course-landing-page */
__('A course needs a page that sells it, or an existing sales page has drifted out of step with the curriculum.', 'nibwp');
/* translators: Skill description: seo-pro */
__('A guided SEO workflow, not just field access. Scan the whole site for a scored report card, generate brand-voice titles + meta descriptions that pass length + uniqueness validation, build and validate structured data, fix canonicals/robots/alt text in bulk, migrate meta between SEO plugins, and gate drafts before publish. Every write runs through a dry-run → validate → commit pipeline so nothing bad lands.', 'nibwp');
/* translators: Workflow when to use: performance-tune */
__('A site feels slow or fails Core Web Vitals.', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('ACSS / Bricks design-token output with fallback values', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('ACSS-ready output — mapped to tokens with safe fallback values', 'nibwp');
/* translators: Workflow when to use: contact-form */
__('Adding a contact or lead-capture form to a site.', 'nibwp');
/* translators: Workflow when to use: woocommerce-product */
__('Adding or optimizing a WooCommerce product.', 'nibwp');
/* translators: Workflow when to use: safe-changes */
__('Any change to a live, client, or production site.', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Assets sideloaded to your Media Library (2× images, inline SVG icons)', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Assign as a post type\'s main card, a named alternate card, single, archive, header, footer, or a site-wide style kit', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Audit any existing Breakdance page against the same rules', 'nibwp');
/* translators: Skill feature: acss-pro */
__('Audit existing rendered CSS for drift from ACSS tokens', 'nibwp');
/* translators: Skill tagline: seo-pro */
__('Audit, optimize and validate SEO across any engine — Yoast, Rank Math, AIOSEO, SEOPress or Slim SEO — with an AI co-pilot.', 'nibwp');
/* translators: Workflow when to use: site-audit-report */
__('Auditing, reviewing, or debugging an existing site before any change.', 'nibwp');
/* translators: Skill feature: tutorlms-builder */
__('Auto-generate quizzes with valid questions (true/false, single, multiple, open-ended)', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Auto-layout → flexbox/grid, constraints → responsive, effects → box-shadow — mapped natively', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Automatically matches spacing, layout, colors, and typography', 'nibwp');
/* translators: Workflow when to use: automation-setup */
__('Automating a flow: form → email + tag, new order → fulfillment, signup → onboarding sequence.', 'nibwp');
/* translators: Workflow summary: pre-launch-checklist */
__('Backups, security, SEO basics, broken links, performance, and final QA before a site goes live.', 'nibwp');
/* translators: Workflow when to use: pre-launch-checklist */
__('Before taking a site live or handing it off to a client.', 'nibwp');
/* translators: Skill feature: tutorlms-minisite */
__('Bound to the course DTO — title, price, curriculum, instructor pulled in', 'nibwp');
/* translators: Skill feature: acss-pro */
__('Brand color delta-E check to prevent indistinguishable palettes', 'nibwp');
/* translators: Skill feature: seo-pro */
__('Brand-voice SEO titles + meta descriptions (length + uniqueness validated)', 'nibwp');
/* translators: Workflow summary: full-site-build */
__('Brief → sitemap → design tokens → global styles → page-by-page build → nav/footer → QA. The whole stack: EtchWP Pro, ACSS, ACF, forms.', 'nibwp');
/* translators: Workflow when to use: fix-404-redirects */
__('Broken links or 404s after a migration, rename, or restructure.', 'nibwp');
/* translators: Workflow title: figma-to-wordpress */
__('Build a Figma design in WordPress', 'nibwp');
/* translators: Workflow title: course-build */
__('Build a Tutor LMS course', 'nibwp');
/* translators: Workflow title: voxel-directory-build */
__('Build a Voxel directory', 'nibwp');
/* translators: Workflow title: contact-form */
__('Build a contact / lead form', 'nibwp');
/* translators: Workflow title: course-landing-page */
__('Build a course landing page', 'nibwp');
/* translators: Workflow title: full-site-build */
__('Build a full site from a brief', 'nibwp');
/* translators: Workflow summary: course-landing-page */
__('Build a sales page for a Tutor LMS course bound to the live course record — curriculum, instructor and price read from the course rather than retyped — saved as a draft linked back to it.', 'nibwp');
/* translators: Workflow title: automation-setup */
__('Build an automation (trigger → action)', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Build every Voxel template kind — preview card, single post, archive, term, header, footer, search page, style kit', 'nibwp');
/* translators: Workflow title: build-from-screenshot */
__('Build from a screenshot / image', 'nibwp');
/* translators: Skill description: voxel-pro */
__('Build the templates a Voxel site is made of. The agent composes an Elementor document using Voxel\'s own widgets — search form, post feed, map, gallery, work hours, review stats, actions — binds it to real listing data with @tags() dynamic tags, and this skill validates every piece before it is written: widget names against the live registry, filter and field keys against the site\'s own configuration, and every dynamic tag rendered against a real post so a typo can never ship as literal text on the page. Search forms, feeds and maps are wired together automatically, because that wiring lives in post meta and is positional — hand-written paths break the moment anything moves. Assign the result as a post type\'s main card, a named alternate, a single or archive layout, a header, or a site-wide style kit.', 'nibwp');
/* translators: Workflow when to use: page-build-standard */
__('Building any page or section with the site’s page builder.', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Builds into your site\'s active builder — EtchWP, Bricks, Elementor, or Gutenberg core (auto-detected, override anytime)', 'nibwp');
/* translators: Skill feature: seo-pro */
__('Bulk fixes: canonicals, robots, missing meta, image alt text', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Catches the namespace backslash that silently breaks every slug in JSON', 'nibwp');
/* translators: Workflow when to use: voxel-design-card */
__('Changing how listings look in search results, feeds, or map popups.', 'nibwp');
/* translators: Skill feature: design-skills */
__('Color roles computed and corrected to WCAG AA before they reach a page', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Composes enhancer skills automatically when active — acss-pro (native tokens), seo-pro (semantics/meta)', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Conditional rendering built-in for dynamic UI behavior', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Container-first structure — sections and columns become nested containers, widgets go inside', 'nibwp');
/* translators: Workflow title: content-cleanup */
__('Content audit & cleanup', 'nibwp');
/* translators: Workflow title: content-creation */
__('Content creation (research → publish)', 'nibwp');
/* translators: Skill tagline: figma-pro */
__('Convert Figma frames & components into native, maintainable WordPress — reads the real design (node tree + Variables), not a screenshot', 'nibwp');
/* translators: Workflow title: build-from-html */
__('Convert HTML / a URL to components', 'nibwp');
/* translators: Skill tagline: elementor-pro */
__('Convert HTML, URLs, images, or screenshots into native, editable Elementor pages — containers and widgets, not raw HTML', 'nibwp');
/* translators: Skill tagline: kadence-pro */
__('Convert HTML, URLs, images, or screenshots into validated Kadence Blocks layouts, templates, and reusable patterns', 'nibwp');
/* translators: Skill tagline: bricks-pro */
__('Convert HTML, URLs, images, screenshots, or Figma frames into validated Bricks templates with ACSS tokens, global classes, query loops, and dynamic data', 'nibwp');
/* translators: Skill tagline: etchwp-pro */
__('Convert HTML, URLs, images, screenshots, or Figma frames into validated EtchWP components', 'nibwp');
/* translators: Skill tagline: breakdance-pro */
__('Convert HTML, URLs, screenshots or Figma frames into validated Breakdance pages and templates — checked against your own element registry and design tokens', 'nibwp');
/* translators: Workflow title: convert-to-breakdance */
__('Convert a design to Breakdance', 'nibwp');
/* translators: Workflow title: convert-to-bricks */
__('Convert a design to Bricks', 'nibwp');
/* translators: Workflow title: convert-to-elementor */
__('Convert a design to Elementor', 'nibwp');
/* translators: Workflow title: convert-to-kadence */
__('Convert a design to Kadence Blocks', 'nibwp');
/* translators: Workflow title: convert-to-etchwp */
__('Convert a page to EtchWP', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Convert any Figma frame → a WordPress page, or a component → a reusable block', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Convert any live URL into a clean, editable Breakdance template', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Convert any live website URL into a clean, editable Bricks template', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Convert any live website URL into a clean, editable Kadence layout', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Convert any live website URL into a clean, editable component', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Convert any live website URL or raw HTML into a clean, editable Elementor layout', 'nibwp');
/* translators: Workflow when to use: build-from-html */
__('Converting pasted HTML, a Figma export, or a URL into Etch/Bricks components.', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Correct structure enforced — columns only inside rowlayout, buttons only inside advancedbtn', 'nibwp');
/* translators: Skill feature: tutorlms-builder */
__('Course difficulty, duration, prerequisites and instructor assignment', 'nibwp');
/* translators: Workflow title: woocommerce-product */
__('Create a WooCommerce product', 'nibwp');
/* translators: Workflow when to use: course-build */
__('Creating a course from source material, or filling out one that exists as a title and nothing else.', 'nibwp');
/* translators: Workflow title: cpt-and-fields */
__('Custom post type + fields', 'nibwp');
/* translators: Skill tagline: design-skills */
__('Decide how this site should look before anything gets built — so pages stop looking machine-made', 'nibwp');
/* translators: Workflow summary: design-system-setup */
__('Derive a design direction from the site you already have — palette, type scale, spacing rhythm, radii — agree it with the user, and record the brand prefix and colors so every later build references the same tokens instead of inventing values page by page.', 'nibwp');
/* translators: Workflow title: voxel-design-card */
__('Design a Voxel preview card', 'nibwp');
/* translators: Skill tagline: voxel-pro */
__('Design and build Voxel templates — preview cards, single posts, archives, search pages, headers and style kits', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Design-library parts listed so new sections match what is already approved', 'nibwp');
/* translators: Workflow summary: page-build-standard */
__('Detect the builder, build in sections, design tokens not hardcodes, responsive + accessible + fast.', 'nibwp');
/* translators: Workflow summary: contact-form */
__('Detected forms plugin: fields, validation, spam protection, admin + autoresponder email, confirmation, CRM hook, real delivery test.', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Detects repeated components and builds ONE reusable component with dynamic data — never duplicated markup', 'nibwp');
/* translators: Skill feature: design-skills */
__('Direction derived from THIS site — ACSS variables, theme.json, logo colors — not from a template', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Dynamic data tags ({post_title}, {acf:field}, etc.) when CPT context', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Dynamic kadence/posts suggested instead of 3+ repeated static cards', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Element validation against YOUR registry — not a static list that goes stale', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Element whitelist — only real Bricks core elements (section, container, div, heading, text, button, image, icon, video, form, nav-menu, ...)', 'nibwp');
/* translators: Workflow summary: seo-full-audit */
__('End-to-end SEO health check — technical, indexing, on-page, content, internal links, schema, performance — into a scored, prioritized report.', 'nibwp');
/* translators: Skill feature: tutorlms-builder */
__('Engine-aware pricing (free / paid) wired to the active monetization engine', 'nibwp');
/* translators: Workflow title: design-system-setup */
__('Establish the design direction first', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Establishes a design-token system first: Figma Variables → ACSS var(--token) + a type ramp', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Every @tags() dynamic tag rendered against a real listing before the template is saved — no tag ships as literal text', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Every block gets a unique uniqueID (Kadence keys its generated CSS off it)', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Every overwrite keeps a restorable backup of the previous document', 'nibwp');
/* translators: Skill feature: seo-pro */
__('External (optional): Google Search Console, SERP intent, IndexNow', 'nibwp');
/* translators: Skill description: acss-pro */
__('Feed in a design source (screenshot, HTML+CSS, or a live URL) and the agent proposes a complete ACSS configuration — palette, type ramp, space ramp, radius, shadows, breakpoints — validated for WCAG contrast, sane modular scale ratios, and consistent neutral-ramp luminance. Persists to the ACSS settings option after explicit user approval. Pairs with EtchWP Pro: tokens generated here are exactly the ones EtchWP Pro emits in components.', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Figma Variables matched against your own variables by value, so a frame adopts your design system', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Figma frames read as structure — node tree, auto-layout and Variables, not a picture (needs a Figma connection)', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Filter, field and post type keys checked against the site\'s own Voxel configuration, not guessed', 'nibwp');
/* translators: Workflow summary: content-cleanup */
__('Find thin, duplicate, outdated, or cannibalizing content → decide keep / merge / redirect / refresh.', 'nibwp');
/* translators: Workflow title: fix-404-redirects */
__('Fix 404s with 301 redirects', 'nibwp');
/* translators: Skill feature: design-skills */
__('Free, on by default, on every install', 'nibwp');
/* translators: Workflow summary: voxel-directory-build */
__('From a post type to a working directory — fields and filters, then the preview card, single layout, archive and a wired search page, each assigned and each checked against the site\'s own data.', 'nibwp');
/* translators: Workflow title: seo-full-audit */
__('Full SEO audit', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Fully responsive by default — optimized for mobile, tablet, and desktop', 'nibwp');
/* translators: Skill feature: acss-pro */
__('Generate ACSS palette + type ramp + space ramp from a screenshot', 'nibwp');
/* translators: Skill tagline: tutorlms-minisite */
__('Generate a styled landing / sales page for any Tutor LMS course', 'nibwp');
/* translators: Skill tagline: acss-pro */
__('Generate a working ACSS configuration from a screenshot, HTML+CSS, or live URL', 'nibwp');
/* translators: Skill feature: acss-pro */
__('Generate from raw HTML+CSS or a live target URL', 'nibwp');
/* translators: Skill description: tutorlms-builder */
__('Give the agent a topic, an outline, a transcript, a PDF, or a URL and it plans and builds a full Tutor LMS course — topics, lessons, and quizzes with real questions — validated against pedagogy + Tutor schema rules, then persisted via the Tutor LMS integration. Turn any content into a sellable course.', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Global classes (Bricks-native) — BEM-prefixed, brand-scoped', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Headers, footers, popups and templates built WITH their display conditions', 'nibwp');
/* translators: Skill feature: tutorlms-minisite */
__('Hero, what-you-will-learn, curriculum, instructor, pricing, FAQ, enroll CTA', 'nibwp');
/* translators: Workflow summary: site-audit-report */
__('Inspect-only health check → structured Issues / Observations / Suggestions report, prioritized Critical → Note.', 'nibwp');
/* translators: Skill feature: seo-pro */
__('Internal-link suggestions + insertion, broken-link detection', 'nibwp');
/* translators: Skill feature: design-skills */
__('Layout sequences for 20 kinds of WordPress page, from local trade to pricing to case study', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Literal colors and sizes matched against variables you already defined', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Loop support for dynamic lists, cards, and repeating content', 'nibwp');
/* translators: Workflow summary: automation-setup */
__('Map trigger → conditions → actions, build it in the detected automation tool (FluentCRM / Fluent Forms / Woo), test end-to-end, document it.', 'nibwp');
/* translators: Workflow summary: performance-tune */
__('Measure Core Web Vitals, then fix the biggest wins: images, caching, render-blocking assets, slow queries.', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Media sideloaded into your Media Library with real attachment IDs — no hotlinked images', 'nibwp');
/* translators: Skill feature: seo-pro */
__('Migrate SEO meta between Yoast / Rank Math / AIOSEO / SEOPress / Slim SEO', 'nibwp');
/* translators: Workflow when to use: convert-to-etchwp */
__('Migrating or rebuilding existing content (Bricks / Elementor / Divi / WPBakery / Gutenberg / HTML / URL / Figma) into EtchWP.', 'nibwp');
/* translators: Workflow summary: cpt-and-fields */
__('Model new content: register a CPT, add ACF fields, set admin columns, wire templates and queries.', 'nibwp');
/* translators: Workflow when to use: cpt-and-fields */
__('Modeling new structured content with a CPT and custom fields.', 'nibwp');
/* translators: Skill feature: acss-pro */
__('Modular scale ratio sanity (1.067–1.618 only)', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Native Bricks video element — never raw YouTube/Vimeo iframe', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Native elements only — flexbox containers, heading, text-editor, image, button, icon-box, image-box, video, tabs, accordion, and your installed Pro / add-on widgets', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Native form element (or shortcode wrap) — never raw <form>', 'nibwp');
/* translators: Skill feature: acss-pro */
__('Neutral ramp luminance gap enforcement (light/dark ≥ 80%)', 'nibwp');
/* translators: Skill feature: design-skills */
__('Never writes markup — it directs the builder skills rather than competing with them', 'nibwp');
/* translators: Skill feature: seo-pro */
__('On-page optimization for a target keyword with before/after scoring', 'nibwp');
/* translators: Workflow summary: seo-content-pass */
__('One post → keyword/intent → title + meta → headings → internal links → schema → image alt → publish.', 'nibwp');
/* translators: Workflow summary: voxel-design-card */
__('One preview card for a Voxel post type — bound to real field keys, every dynamic tag rendered against a real listing before it is written, assigned as the main card or a named alternate.', 'nibwp');
/* translators: Skill feature: tutorlms-minisite */
__('One styled landing page per course, from the live course data', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Outputs structured, JSON-ready components for direct integration', 'nibwp');
/* translators: Workflow title: page-build-standard */
__('Page build standard', 'nibwp');
/* translators: Skill description: breakdance-pro */
__('Paste HTML, drop a screenshot, share a URL or attach a Figma frame, and the agent rebuilds it as a real Breakdance page, template, header, footer, popup or global block. Every element slug and property path is checked against the registry of your install, not a documentation file — so a typo is an error message rather than a blank section. Literal colors and sizes that match variables you already defined are reported so the section follows your palette. Repeated cards are detected and turned into a loop bound to a post type. Templates are created with their display conditions, because a template with none is invisible. Existing pages can be audited against the same rules and refined one node at a time, without rebuilding work someone already did by hand. Figma frames are read from the file — node tree, auto-layout and Variables — rather than looked at as a picture, and Figma Variables are matched against yours by value so a frame adopts your design system instead of pasting hex codes; that path needs a Figma connection, and the skill says so plainly rather than quietly producing screenshot-quality output. Works on Oxygen 6 too.', 'nibwp');
/* translators: Skill description: kadence-pro */
__('Paste raw HTML, drop a screenshot, or share a URL — the agent rebuilds it as a clean Kadence Blocks layout (rowlayout/column sections, advancedheading, singlebtn, image, infobox, iconlist, testimonials…). A hard validator rejects unknown block names, illegal nesting (column outside rowlayout, button outside advancedbtn), missing/duplicate uniqueIDs, and empty headings/buttons; a round-trip guard makes sure no block is ever dropped on save. Persist to a page, post, Kadence Element (header/footer/hook), or a reusable pattern.', 'nibwp');
/* translators: Skill description: elementor-pro */
__('Paste raw HTML, drop a screenshot, or share a URL — the agent rebuilds it as a clean, native Elementor page: modern flexbox containers first, then real widgets (heading, text-editor, image, button, icon-box, image-box, video, tabs, accordion, and any Pro/add-on widget your site actually has). Every widget type and control id is checked against the LIVE Elementor registry on your site, so nothing is invented. Styling maps to Elementor controls (padding, gap, background, typography, colors) — not a wall of custom CSS. A hard validator rejects unknown widget types, invalid control names, broken hierarchy and duplicate ids; the persister writes the data the way Elementor needs it (correctly slashed, edit-mode enabled, CSS regenerated) with a round-trip guard so a page is never saved truncated.', 'nibwp');
/* translators: Skill description: bricks-pro */
__('Paste raw HTML, drop a screenshot, share a URL, or attach a Figma frame — the agent rebuilds it as a clean Bricks template or section. Loop detection turns repeated cards into a Bricks Query Loop + CPT + ACF fields. Native Bricks elements (form, video, nav-menu) replace raw <form> / <iframe> / nav HTML. Hard validator rejects unknown element names, inline styles, hardcoded colors / font-sizes outside var() fallback, missing global classes, and static text where dynamic data is available.', 'nibwp');
/* translators: Skill description: etchwp-pro */
__('Paste raw HTML, drop a screenshot, share a URL, or attach a Figma frame — the agent rebuilds it as a clean, brand-consistent EtchWP component. Loop detection turns repeated cards into CPT + ACF + Etch loop blocks automatically. The validator rejects clamp() font-size, hardcoded colors, raw <style> tags, and missing brand prefixes before anything persists.', 'nibwp');
/* translators: Skill feature: tutorlms-builder */
__('Pedagogy + Tutor-schema validation before anything is written', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Per-breakpoint settings via Bricks built-in editor — never inline @media', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Per-element checklist enforced server-side before persist', 'nibwp');
/* translators: Workflow title: performance-tune */
__('Performance tune-up', 'nibwp');
/* translators: Skill feature: acss-pro */
__('Persist to ACSS settings option (with explicit user approval)', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Persist to a page, post, Kadence Element (header/footer/hook), or reusable pattern', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Persisted the way Elementor needs it — correctly slashed data, edit-mode on, CSS regenerated, so the page renders immediately', 'nibwp');
/* translators: Skill feature: tutorlms-builder */
__('Persists through the audited Tutor LMS integration write paths', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Pixel-diff verified — renders the built page and compares it to Figma\'s export, then iterates', 'nibwp');
/* translators: Skill feature: bricks-pro; Skill feature: etchwp-pro */
__('Pixel-perfect recreation that stays faithful to the original design', 'nibwp');
/* translators: Skill feature: tutorlms-builder */
__('Plan a full course curriculum from a brief, outline, transcript, PDF or URL', 'nibwp');
/* translators: Workflow summary: safe-changes */
__('Plan first, explain the impact, get explicit approval, apply, summarize, and always leave a rollback path.', 'nibwp');
/* translators: Skill description: figma-pro */
__('Point NibWP at a Figma URL, frame, or component and get a native WordPress build in your site\'s own builder. figma-pro reads the actual Figma document — auto-layout, constraints, Variables, styles — parses it into an internal design object, establishes a real design-token system (Variables → ACSS tokens), dedupes repeated components into reusable blocks with dynamic data, then drives the active builder skill (EtchWP / Bricks / Elementor / Gutenberg) to build it. The result is verified by rendering the page and image-diffing it against Figma\'s own export — pixel-perfect, not "close enough". Read-only in v1 (write-back to Figma is a later phase). Composes active enhancer skills automatically: acss-pro for a native token system, seo-pro for semantics/meta.', 'nibwp');
/* translators: Skill description: tutorlms-minisite */
__('Point it at a Tutor LMS course and it builds a polished landing micro-site — hero, what-you-will-learn, curriculum, instructor, pricing, FAQ and an enroll CTA — bound to the live course data and saved as a WordPress page linked to the course.', 'nibwp');
/* translators: Workflow title: pre-launch-checklist */
__('Pre-launch checklist', 'nibwp');
/* translators: Skill feature: seo-pro */
__('Pre-publish SEO gate (pass/fail) before content goes live', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Preserves interactions like hover states, animations, and accordions', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Production-grade BEM structure for clean, scalable architecture', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Property paths checked against each element\'s real control schema', 'nibwp');
/* translators: Workflow when to use: content-cleanup */
__('Pruning or consolidating a large content library.', 'nibwp');
/* translators: Workflow when to use: seo-content-pass */
__('Publishing or optimizing a single post or page for search.', 'nibwp');
/* translators: Workflow summary: fix-404-redirects */
__('Pull the 404 log, group by intent, map each to the best live target, create 301s, verify.', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Query loops backed by CPT + ACF — no static repetition', 'nibwp');
/* translators: Workflow summary: figma-to-wordpress */
__('Read the real Figma node tree and Variables — not a screenshot — map them to the design tokens this site already uses, detect which builder it runs, and convert through the validated pipeline belonging to that builder.', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Reads private Figma files via your own account token; read-only, persisted as a draft with a backup', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Reads the real Figma node tree + Variables (not a screenshot) — structure and tokens are derived, not guessed', 'nibwp');
/* translators: Skill description: design-skills */
__('Reads what this site already has — ACSS variables, theme.json palette and type scale, the logo — and turns it into a design direction: color roles with contrast already validated to WCAG AA, a type pairing, spacing rhythm, shape language, the layout sequence that suits this kind of page, and the specific generic defaults to refuse. Where the site says nothing, it falls back to a design catalogue seeded per site, so two installs never start from the same place. The direction is remembered, so page two matches page one. Free, on by default, and it never writes markup — it tells whichever builder skill is doing the work how the work should look.', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Real Kadence blocks only — rowlayout, column, advancedheading, singlebtn, image, infobox, iconlist, accordion, tabs, testimonials, posts, gallery…', 'nibwp');
/* translators: Workflow summary: convert-to-breakdance */
__('Rebuild HTML, a URL, a screenshot, or a Figma frame as a native Breakdance section via the Breakdance Pro skill — real nodes in the builder tree rather than markup in the post body, element types read from the live catalogue, then audited.', 'nibwp');
/* translators: Workflow summary: convert-to-bricks */
__('Rebuild HTML, a URL, a screenshot, or a Figma frame as a native Bricks template via the Bricks Pro skill — real elements, styling in element settings rather than custom CSS, BEM global classes, per-breakpoint values, validated then committed.', 'nibwp');
/* translators: Workflow summary: convert-to-elementor */
__('Rebuild HTML, a URL, or a screenshot as native Elementor widgets via the Elementor Pro skill — widget names and control ids read from the live registry, classic and V4 atomic elements both supported, render-checked after the write.', 'nibwp');
/* translators: Workflow summary: convert-to-kadence */
__('Rebuild HTML, a URL, or a screenshot as native Kadence Blocks via the Kadence Pro skill — real blocks (rowlayout/column/advancedheading/singlebtn/infobox…), correct nesting, unique IDs, attribute styling, validated + scored, persisted to a page, template, or pattern.', 'nibwp');
/* translators: Workflow summary: convert-to-etchwp */
__('Rebuild a page from another builder, Gutenberg, HTML, a URL, or Figma as native EtchWP — ACSS tokens, global classes, query loops, native elements, validated + parity-checked.', 'nibwp');
/* translators: Workflow summary: build-from-html */
__('Rebuild raw HTML or a live URL as clean builder components via the EtchWP Pro / Bricks Pro skill — no inline styles, real elements, design tokens.', 'nibwp');
/* translators: Workflow when to use: convert-to-breakdance */
__('Rebuilding a design (HTML / URL / image / Figma) into a Breakdance page or section.', 'nibwp');
/* translators: Workflow when to use: convert-to-bricks */
__('Rebuilding a design (HTML / URL / image / Figma) into a Bricks page, template, header, or footer.', 'nibwp');
/* translators: Workflow when to use: convert-to-kadence */
__('Rebuilding a design (HTML / URL / image) into a Kadence Blocks layout, template, or reusable pattern.', 'nibwp');
/* translators: Workflow when to use: build-from-screenshot */
__('Rebuilding a design from a screenshot, mockup, or image into the site builder.', 'nibwp');
/* translators: Workflow when to use: convert-to-elementor */
__('Rebuilding a design into an Elementor page or template, or repairing one that will not open in the editor.', 'nibwp');
/* translators: Workflow summary: build-from-screenshot */
__('Recreate a design from a screenshot or image as a real, validated page/section — EtchWP Pro + ACSS tokens, responsive, accessible, pixel-accurate.', 'nibwp');
/* translators: Skill feature: tutorlms-builder */
__('Refine an existing course or lesson with a natural-language instruction', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Refine an existing layout by written instruction', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Refine an existing template surgically: change one setting, add a visibility rule, insert or move an element', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Refine one node at a time — never rebuild a page to change a heading', 'nibwp');
/* translators: Skill feature: design-skills */
__('Remembers the direction, so a whole site reads as designed rather than assembled', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Repeated cards detected and planned as a loop bound to a post type', 'nibwp');
/* translators: Workflow summary: content-creation */
__('Research the topic + SERP → brief → outline → draft in brand voice → media + alt → SEO pass → internal links → schedule.', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Responsive by default — desktop / tablet / mobile values, not desktop-only', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Reusable component system — not one-off builds', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Reusable section templates — not one-off paste', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Round-trip guard — never saves a truncated page', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Round-trip serialization guard — never persist a truncated page', 'nibwp');
/* translators: Workflow title: seo-content-pass */
__('SEO content pass', 'nibwp');
/* translators: Workflow title: safe-changes */
__('Safe changes (plan → approve → apply)', 'nibwp');
/* translators: Skill feature: tutorlms-minisite */
__('Saved as a draft WordPress page linked back to the course', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Search form, feed and map wired together for you (the wiring lives in post meta, and its paths are positional)', 'nibwp');
/* translators: Workflow title: site-audit-report */
__('Site audit (read-only report)', 'nibwp');
/* translators: Skill feature: seo-pro */
__('Site-wide SEO audit with a 0-100 score + prioritized fix queue', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Smart component props for flexible variants (size, style, visibility)', 'nibwp');
/* translators: Workflow when to use: figma-to-wordpress */
__('Someone pastes a Figma link, or wants a frame, component or library turned into a WordPress page or design system.', 'nibwp');
/* translators: Skill feature: design-skills */
__('Speaks your builder — Etch, Bricks, Elementor, Kadence or core blocks, with the right tokens for each', 'nibwp');
/* translators: Workflow when to use: full-site-build */
__('Standing up a multi-page site from a brief or sitemap.', 'nibwp');
/* translators: Workflow when to use: voxel-directory-build */
__('Standing up a new listing type on a Voxel site, or rebuilding one end to end.', 'nibwp');
/* translators: Workflow when to use: design-system-setup */
__('Starting a site or redesign, before a run of page builds, or when a site has drifted into three greys and five spacing values.', 'nibwp');
/* translators: Skill feature: seo-pro */
__('Structured-data generation + schema.org validation, rendered on any engine', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Style kits (popup and timeline) require an explicit confirmation — they restyle the whole site', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Styling as Elementor controls (padding, gap, background, typography, color) — minimal custom CSS', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Styling as native Kadence attributes (padding, background, color, typography) — no separate CSS to write', 'nibwp');
/* translators: Skill feature: design-skills */
__('The anti-generic list: centred hero, three cards, purple gradient, uniform padding, full-width text — each refused with the reason why', 'nibwp');
/* translators: Skill feature: tutorlms-minisite */
__('Theme-neutral, self-contained output (no page builder required)', 'nibwp');
/* translators: Skill feature: tutorlms-builder */
__('Topics → lessons hierarchy with real lesson content', 'nibwp');
/* translators: Skill tagline: tutorlms-builder */
__('Turn a brief, outline, transcript or URL into a complete, validated Tutor LMS course', 'nibwp');
/* translators: Workflow summary: course-build */
__('Turn a brief, outline, transcript, PDF or URL into a complete validated Tutor LMS course — topics, lessons with real content, and quizzes whose questions come from the lessons before them.', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Turn screenshots and images into working Breakdance pages', 'nibwp');
/* translators: Skill feature: bricks-pro */
__('Turn screenshots or images into fully working Bricks templates', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Turn screenshots or images into fully working Elementor pages', 'nibwp');
/* translators: Skill feature: etchwp-pro */
__('Turn screenshots or images into fully working EtchWP components', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Turn screenshots or images into fully working Kadence Blocks layouts', 'nibwp');
/* translators: Skill feature: figma-pro */
__('Two read sources: Figma REST (headless default) or Figma Dev Mode MCP (live in-app context)', 'nibwp');
/* translators: Workflow summary: woocommerce-product */
__('Type → pricing → images + alt → description → attributes/variations → inventory → SEO/schema → categories → publish.', 'nibwp');
/* translators: Skill feature: kadence-pro */
__('Validate + score before you commit (dry-run)', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Validate + score before you commit (dry-run); read an existing page structure; refine by instruction', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Validate and score before you commit (dry-run)', 'nibwp');
/* translators: Skill feature: tutorlms-minisite */
__('Validated structure before anything is written', 'nibwp');
/* translators: Skill feature: voxel-pro */
__('Voxel\'s own widgets, used properly — search form, post feed, map, create post, gallery, work hours, review stats, actions, navbar, user bar', 'nibwp');
/* translators: Skill feature: acss-pro */
__('WCAG AA contrast validation on heading/body pairs', 'nibwp');
/* translators: Skill feature: elementor-pro */
__('Widget types + control ids validated against the LIVE Elementor registry on your site (nothing guessed, Pro-aware)', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('WooCommerce element catalogue for store templates', 'nibwp');
/* translators: Skill feature: breakdance-pro */
__('Works on Oxygen 6 — same codebase, different brand', 'nibwp');
/* translators: Workflow when to use: content-creation */
__('Writing a new article or page from scratch.', 'nibwp');
